### ISSUE TITLE
Concerning http://skyescribbles.com/skyescribbles.com/

### ISSUE THREAD

**Issue by samasaurus6** [FeyberryJam/FeyberryJam.github.io#2]
needs more ascii porn/nudes

**Comment by FeyberryJam** [comment]
Lol she won't let me >.<

**Comment by FeyberryJam** [comment]
Please continue supporting us in our new location!

Project moved to: https://github.com/FeyberryJam/skyescribbles.com
Url changed to: http://skyescribbles.com/portfolio/
